### ISSUE TITLE
UBIF-0004 SVGs do not appear after drawn on Google Maps when they are small

### ISSUE THREAD

**Issue by glenpierce** [glenpierce/UBHub#64]
**Describe the bug**
SVGs of the drawn polygons in the UBIF 2.0 Project are not being rendered in the habitat details panels below the map.

**To Reproduce**
1. Go to UBIF 2.0 Project creation page
2. Click on Google Map
3. Zoom into a very small area, like a city block.
4. Draw a small polygon, perhaps only the size of someone's backyard for example.

**Expected behavior**
The Habitat Panel should contain small versions of those SVGs so users can easily differentiate between them. ***If it is easier or more reasonable, could we render a new Google Map?***

**Screenshots**
![svgs should show up below the map too](https://user-images.githubusercontent.com/6483714/58854781-26085a80-8653-11e9-9432-9d6d833942a8.PNG)

**Additional context**
The technical problem is explained in this stack overflow post: https://stackoverflow.com/questions/55803931/why-cant-i-see-the-polygon-drawn-in-this-svg-and-how-can-i-make-it-visible?noredirect=1#comment98276805_55803931

**Comment by paradalis** [comment]
love to see this. remember we could try avoiding this problem by just making small maps instead of redrawing the shape in isolation. this may actually be better.

Best,
---
Jennifer Rae Pierce
Political Ecologist and Urban Planner
PhD student, School of Community and Regional Planning, UBC
Skype: biodivercities
@nestcities
