### ISSUE TITLE
UBIF-0006 Update web page structure to match specs

### ISSUE THREAD

**Issue by paradalis** [glenpierce/UBHub#65]
The UBIF web page should have three parts, each viewed separately, as per the web structure indicated in the Wiki. It should feel like 3 "pages" even if they are all on the same url. THis could be done with the same "drop down" arrows we use in other parts of the UBHub site, such as on the /resources page.

**Comment by glenpierce** [comment]
Spec: https://github.com/glenpierce/UBHub/wiki/UBIF-Track-2-Indicator-Tracker-Web-Page-Structure

**Comment by glenpierce** [comment]
Currently sticky header is being prototyped. We could go with horizontal tabs across the top or sticky header & footer.

**Comment by glenpierce** [comment]
I've got the headers working well enough now, but I'm having some issues with the overall structure as defined in the spec referenced here: https://github.com/glenpierce/UBHub/wiki/UBIF-Track-2-Indicator-Tracker-Web-Page-Structure Mostly this is due to the fact that I haven't built all of those parts yet. I suspect we'll see the page I'm working on grow as I build it out and it will eventually match what we're looking for.
