### ISSUE TITLE
Fix google map failing to load in Production

### ISSUE THREAD

**Issue by glenpierce** [glenpierce/UBHub#8]
In Production only, the google map fails to load quite often for users. This never seems to happen in the development environment. Might have something to do with how we're loading the google maps javascript.

**Comment by av2335** [comment]
My initial hunch is that things are loading out of order.

From line 5 of map.jade:
"script(async, defer, src="https://maps.googleapis.com..."

It seems like "defer" would prevent things from loading out of order.  I googled "async and defer" because their interaction wasn't clear, and found this, from W3.org:
"The defer attribute may be specified even if the async attribute is specified, to cause legacy Web browsers that only support defer (and not async) to fall back to the defer behavior instead of the synchronous blocking behavior that is the default."

So it looks like, on most browsers, async might negate defer.  If that happens, is it possible the response is arriving from googlemaps before the page is ready to handle it?  The script calls back initMap() - I'm still figuring out a lot of this timing stuff, but is it possible it is calling initMap() when it hasn't been loaded yet?

**Comment by av2335** [comment]
@glenpierce - Forgot to poke you when I commented on this.

Since the issue happens only in production, how should we handle testing this?  If I put together a few possible solutions, can you throw them into production and test?

**Comment by glenpierce** [comment]
@av2335 Sounds like you're proposing that we change line 5 of map.jade from:
"script(async, defer, src="https://maps.googleapis.com..."
to:
"script(defer, src="https://maps.googleapis.com..."
right?

**Comment by av2335** [comment]
@glenpierce 

That change should solve the problem.  Might be excessive, though.  There shouldn't be any reason we can't get the async to work.

Option 2 would be to move that line to anywhere else in the document after the 'map' div exists (line 61).  The cleanest place would probably be at the end of the HTML.

Option 3 - maybe the best solution in the long run - would be to do an event listener which fires off the map request once the page is fully loaded.  Shouldn't be more than a few lines of code, but, since these other two options are only a line each, we might as well try them first.  If nothing else, should let us know if the problem is what I think it is.

**Comment by glenpierce** [comment]
Option 3 has the significant advantage that it can be tested in a local environment. Otherwise, we're just hoping that Option 1 works. Not sure if Option 2 will work.
